"""Gmsh ``.geo`` writer for axisymmetric wedge fluid domains."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from geometry.boundary_mapper import render_post_extrusion_physical_group_lines
from geometry.constants import COORD_PRECISION
from geometry.mesh_settings import ProductionMeshSettings, ScaledMeshSizes
from geometry.wedge_geometry import BSplineCurve, CurveRole, LineCurve, WedgeMeridionalDomain


def _format_coord(value: float) -> str:
    """Format a coordinate for Gmsh point definitions."""
    return f"{value:.{COORD_PRECISION}f}"


@dataclass
class GeoWriter:
    """Emit a wedge fluid-domain ``.geo`` file from a validated meridional model."""

    domain: WedgeMeridionalDomain
    global_size: float
    mesh_settings: ProductionMeshSettings | None = None
    profile_xmin: float = 0.0
    profile_xmax: float = 0.0
    profile_ymax: float = 0.0
    _lines: list[str] | None = None

    def _emit(self, line: str = "") -> None:
        assert self._lines is not None
        self._lines.append(line)

    def _scaled_sizes(self) -> ScaledMeshSizes | None:
        if self.mesh_settings is None or not self.mesh_settings.is_production:
            return None
        length = self.profile_xmax - self.profile_xmin
        return self.mesh_settings.scaled(length)

    def _bl_enabled(self) -> bool:
        sizes = self._scaled_sizes()
        return sizes is not None and sizes.bl_enabled

    def _wall_loop_indices(self) -> tuple[int, ...]:
        """Indices of rocket_wall curves inside the meridional outer loop."""
        indices: list[int] = []
        curves_by_tag = {curve.tag: curve for curve in self.domain.all_curves}
        for index, raw_tag in enumerate(self.domain.outer_loop.curve_tags):
            curve = curves_by_tag[abs(raw_tag)]
            if curve.role is CurveRole.ROCKET_WALL:
                indices.append(index)
        return tuple(indices)

    def _write_header(self) -> None:
        angle = self.domain.wedge_angle_deg
        self._emit("// Rocket wedge fluid domain generated by csv_to_geo.py")
        self._emit(
            f"// {angle}-degree axisymmetric wedge; mesh with: gmsh <file>.geo -3"
        )
        sizes = self._scaled_sizes()
        if sizes is not None:
            self._emit(
                f"// Production mesh level {sizes.level.value}; "
                f"lc_far = {_format_coord(sizes.lc_far)} m (L = {_format_coord(sizes.length)} m)"
            )
            if sizes.bl_enabled:
                self._emit(
                    f"// BL: h0={_format_coord(sizes.bl_first_layer)} m, "
                    f"r={_format_coord(sizes.bl_growth_ratio)}, "
                    f"N={sizes.bl_n_layers}, "
                    f"thickness={_format_coord(sizes.bl_thickness)} m"
                )
            self._emit(f"lc = {_format_coord(sizes.lc_far)};")
        else:
            self._emit(
                "// Debug uniform mesh size — not for production CFD drag studies."
            )
            self._emit(f"lc = {_format_coord(self.global_size)};")
        self._emit('SetFactory("OpenCASCADE");')
        self._emit("")

    def write_points(self) -> None:
        """Emit wall profile points and rectangular far-field corners."""
        sizes = self._scaled_sizes()
        point_lc = sizes.lc_far if sizes is not None else self.global_size

        self._emit(
            "// --- Rocket wall profile points "
            "(upper meridional half, x–r plane, z = 0) ---"
        )
        for point in self.domain.wall_points:
            self._emit(
                f"Point({point.tag}) = {{{_format_coord(point.x)}, "
                f"{_format_coord(point.y)}, {_format_coord(point.z)}, "
                f"{_format_coord(point_lc)}}};"
            )
        self._emit("")

        self._emit("// --- Rectangular fluid-domain corners ---")
        for point in self.domain.corners:
            self._emit(
                f"Point({point.tag}) = {{{_format_coord(point.x)}, "
                f"{_format_coord(point.y)}, {_format_coord(point.z)}, "
                f"{_format_coord(point_lc)}}};"
            )
        self._emit(
            f"// Meridional axis boundary at r = {_format_coord(self.domain.axis_radius)} "
            "(mesh-scaled; avoids degenerate Extrude edges on r = 0)"
        )
        self._emit("")

    @staticmethod
    def _write_bspline(curve: BSplineCurve) -> str:
        control = ", ".join(str(tag) for tag in curve.point_tags)
        return f"BSpline({curve.tag}) = {{{control}}};"

    @staticmethod
    def _write_line(curve: LineCurve) -> str:
        return f"Line({curve.tag}) = {{{curve.start}, {curve.end}}};"

    def write_curves(self) -> None:
        """Emit wall B-spline segments and far-field boundary lines."""
        self._emit("// --- Curves ---")
        self._emit("// Chained wall B-splines through upper meridional profile points")
        for curve in self.domain.wall_curves:
            self._emit(self._write_bspline(curve))

        for curve in (
            self.domain.axis_left,
            self.domain.axis_right,
            self.domain.outlet,
            self.domain.farfield_top,
            self.domain.inlet,
        ):
            self._emit(self._write_line(curve))
        self._emit("")

    def write_surface(self) -> None:
        """Emit the closed meridional fluid surface."""
        loop = self.domain.outer_loop
        curve_list = ", ".join(str(tag) for tag in loop.curve_tags)
        self._emit(
            "// --- Meridional plane surface (fluid region above symmetry axis) ---"
        )
        self._emit(f"Curve Loop({loop.tag}) = {{{curve_list}}};")
        surface = self.domain.fluid_surface
        self._emit(f"Plane Surface({surface.tag}) = {{{surface.loop_tag}}};")
        self._emit("")

    def write_rotation(self) -> None:
        """Rotate a duplicate of the meridional surface to −θ/2 (wedge front)."""
        angle = self.domain.wedge_angle_deg
        surface_tag = self.domain.fluid_surface.tag
        wedge_front_name = self.domain.fluid_surface.name
        self._emit("// --- Center meridional surface about the x–z plane ---")
        self._emit(
            f"// wedge_angle_deg = {angle}; rotation axis = x-axis; "
            "centered about x–z plane"
        )
        self._emit(f"wedge_angle_rad = Pi/{int(180 / angle)};")
        self._emit(
            f"// Duplicate Surface{{{surface_tag}}} and rotate copy by -wedge_angle/2"
        )
        self._emit(
            f"rot[] = Rotate{{{{1, 0, 0}}, {{0, 0, 0}}, -wedge_angle_rad/2}}"
            f"{{ Duplicata{{ Surface{{{surface_tag}}}; }} }};"
        )
        self._emit("")
        self._emit(f'Physical Surface("{wedge_front_name}") = {{rot[0]}};')
        self._emit("")

    def write_extrude_volume(self) -> None:
        """Revolve the rotated meridional surface into the wedge volume."""
        sizes = self._scaled_sizes()
        bl_enabled = sizes is not None and sizes.bl_enabled
        self._emit("// --- Revolve into wedge volume ---")
        if bl_enabled:
            # Gmsh BoundaryLayer is 2D-only. Extrude with Layers{1} propagates
            # the meridional BL (quads/tris) into prism/hex columns. Recombine
            # yields hexes from BL quads and prisms from triangular core cells.
            self._emit(
                "// Layers{1}+Recombine: single circumferential layer; "
                "meridional BL → wall-normal prisms/hexes"
            )
            self._emit(
                "ext[] = Extrude{{1, 0, 0}, {0, 0, 0}, wedge_angle_rad}{"
            )
            self._emit("  Surface{rot[0]};")
            self._emit("  Layers{1};")
            self._emit("  Recombine;")
            self._emit("};")
        else:
            self._emit(
                "ext[] = Extrude{{1, 0, 0}, {0, 0, 0}, wedge_angle_rad}"
                "{ Surface{rot[0]}; };"
            )
        self._emit("")

    def write_extrusion(self) -> None:
        """Rotate then extrude (legacy combined entry point)."""
        self.write_rotation()
        self.write_extrude_volume()

    def _write_post_extrusion_physical_groups(self) -> None:
        """Map extruded lateral surfaces to boundary roles via parent curves."""
        self._emit("// --- Post-extrusion physical groups ---")
        for line in render_post_extrusion_physical_group_lines(self.domain):
            self._emit(line)
        self._emit("")

    def write_post_extrusion_physical_groups(self) -> None:
        """Emit post-extrusion physical groups (must follow volume extrusion)."""
        self._write_post_extrusion_physical_groups()

    def _emit_rotated_wall_curve_arrays(self) -> None:
        """Identify rocket_wall curves on the rotated front surface.

        ``Duplicata`` + ``Rotate`` remaps curve tags. Loop order is preserved,
        so wall curves are selected by their indices in the meridional outer loop.
        """
        wall_indices = self._wall_loop_indices()
        if not wall_indices:
            raise RuntimeError("No rocket_wall curves found in meridional outer loop")

        self._emit(
            "// Wall curves on rotated front (loop-order indices after Duplicata)"
        )
        self._emit("rot_bnd[] = Abs(CombinedBoundary{ Surface{rot[0]}; });")
        refs = ", ".join(f"rot_bnd[{i}]" for i in wall_indices)
        self._emit(f"bl_wall_curves[] = {{{refs}}};")
        self._emit("bl_wall_points[] = PointsOf{ Curve{bl_wall_curves[]}; };")
        self._emit("")

    def write_mesh_size_fields(self, *, use_rotated_wall: bool = False) -> None:
        """Emit Gmsh background fields for production mesh levels."""
        sizes = self._scaled_sizes()
        if sizes is None:
            return

        if use_rotated_wall:
            self._emit_rotated_wall_curve_arrays()
            wall_curve_tags = "{bl_wall_curves[]}"
        else:
            wall_curve_tags = ", ".join(
                str(curve.tag) for curve in self.domain.wall_curves
            )
            wall_curve_tags = f"{{{wall_curve_tags}}}"

        xmin = self.profile_xmin
        xmax = self.profile_xmax
        ymax = self.profile_ymax
        nose_x_max = xmin + sizes.nose_extent
        wake_x_min = xmax
        wake_x_max = xmax + sizes.wake_extent
        y_top = self.domain.corners[2].y
        box_y_max = max(ymax * 1.5, y_top * 0.35)
        box_thickness = 0.05 * sizes.length

        self._emit("// --- Production mesh size fields ---")
        self._emit("Field[1] = Distance;")
        self._emit(f"Field[1].CurvesList = {wall_curve_tags};")
        self._emit("Field[1].Sampling = 200;")
        # Near-body volume envelope (coarser than wall strip).
        self._emit("Field[2] = Threshold;")
        self._emit("Field[2].InField = 1;")
        self._emit(f"Field[2].SizeMin = {_format_coord(sizes.lc_min)};")
        self._emit(f"Field[2].SizeMax = {_format_coord(sizes.lc_far)};")
        self._emit("Field[2].DistMin = 0;")
        self._emit(f"Field[2].DistMax = {_format_coord(sizes.near_body_extent)};")
        self._emit("Field[2].Sigmoid = 1;")
        self._emit("Field[3] = Box;")
        self._emit(f"Field[3].VIn = {_format_coord(sizes.lc_nose)};")
        self._emit(f"Field[3].VOut = {_format_coord(sizes.lc_far)};")
        self._emit(f"Field[3].XMin = {_format_coord(xmin - 0.02 * sizes.length)};")
        self._emit(f"Field[3].XMax = {_format_coord(nose_x_max)};")
        self._emit("Field[3].YMin = 0.00000000;")
        self._emit(f"Field[3].YMax = {_format_coord(box_y_max)};")
        self._emit(f"Field[3].Thickness = {_format_coord(box_thickness)};")
        self._emit("Field[4] = Box;")
        self._emit(f"Field[4].VIn = {_format_coord(sizes.lc_wake)};")
        self._emit(f"Field[4].VOut = {_format_coord(sizes.lc_far)};")
        self._emit(f"Field[4].XMin = {_format_coord(wake_x_min)};")
        self._emit(f"Field[4].XMax = {_format_coord(wake_x_max)};")
        self._emit("Field[4].YMin = 0.00000000;")
        self._emit(f"Field[4].YMax = {_format_coord(box_y_max)};")
        self._emit(f"Field[4].Thickness = {_format_coord(box_thickness * 1.6)};")
        # Dedicated wall-strip field: 5° revolved rocket_wall is thinner than
        # lc_min, so volume SizeMin alone yields only a single triangle row.
        self._emit("Field[6] = Threshold;")
        self._emit("Field[6].InField = 1;")
        self._emit(f"Field[6].SizeMin = {_format_coord(sizes.lc_wall)};")
        self._emit(f"Field[6].SizeMax = {_format_coord(sizes.lc_far)};")
        self._emit("Field[6].DistMin = 0;")
        self._emit(f"Field[6].DistMax = {_format_coord(sizes.wall_extent)};")
        self._emit("Field[6].Sigmoid = 1;")
        self._emit("Field[5] = Min;")
        self._emit("Field[5].FieldsList = {2, 3, 4, 6};")
        if sizes.bl_enabled:
            # BoundaryLayer field is 2D-only (Gmsh). Combined with Extrude
            # Layers{1} it creates wall-normal prism/hex inflation.
            self._emit("Field[7] = BoundaryLayer;")
            self._emit("Field[7].CurvesList = {bl_wall_curves[]};")
            self._emit(f"Field[7].Size = {_format_coord(sizes.bl_first_layer)};")
            self._emit(f"Field[7].SizeFar = {_format_coord(sizes.lc_min)};")
            self._emit(f"Field[7].Ratio = {_format_coord(sizes.bl_growth_ratio)};")
            self._emit(f"Field[7].Thickness = {_format_coord(sizes.bl_thickness)};")
            self._emit("Field[7].Quads = 1;")
            self._emit("Field[7].PointsList = {bl_wall_points[]};")
            self._emit("BoundaryLayer Field = 7;")
        self._emit("Background Field = 5;")
        self._emit("")

    def write_mesh_options(self) -> None:
        """Emit meshing options."""
        self._emit("// --- Mesh options ---")
        if self._bl_enabled():
            # Algorithm 8 (Frontal-Delaunay for Quads) pairs with BoundaryLayer Quads=1.
            self._emit("Mesh.Algorithm = 8;")
            self._emit(
                "// 3D topology from Extrude Layers — no free tet fill of the wedge"
            )
        else:
            self._emit(
                "// Recombination disabled — tet wedge mesh for gmshToFoam compatibility"
            )
        self._emit("")

    def render(self) -> str:
        """Build the complete ``.geo`` file contents."""
        self._lines = []
        bl_enabled = self._bl_enabled()
        self._write_header()
        self.write_points()
        self.write_curves()
        self.write_surface()
        self.write_rotation()
        if bl_enabled:
            # Size fields + BoundaryLayer must precede Extrude Layers so the
            # source surface mesh carries wall-normal inflation.
            self.write_mesh_size_fields(use_rotated_wall=True)
            self.write_extrude_volume()
            self.write_post_extrusion_physical_groups()
        else:
            self.write_extrude_volume()
            self.write_post_extrusion_physical_groups()
            self.write_mesh_size_fields(use_rotated_wall=False)
        self.write_mesh_options()
        return "\n".join(self._lines)

    def write_file(self, output_path: Path) -> Path:
        """Write the ``.geo`` file to disk."""
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(self.render(), encoding="utf-8")
        return output_path
